# -*- coding: utf-8 -*-

import unittest

from HTMLTestRunner import HTMLTestRunner
from test_managespace import Testmanagespace
from test_spacebooking import Testspacebooking
import config
import initenv


if __name__ == '__main__':
    suite = unittest.TestSuite()
    # testspacebookings = [Testspacebooking("test_1createbooking"), Testspacebooking("test_2canclebooking")]
    testmanagespaces = [Testmanagespace("test_createspace"), Testmanagespace("test_deletespace")]
    # suite.addTests(testspacebookings)
    suite.addTests(testmanagespaces)
    with open('HTMLReport.html', 'wb') as tf:
        runner = HTMLTestRunner(stream=tf,
                                title='Roomis Test Report',
                                description='Roomis Test Report generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)
# def tearDown(self):
#     initenv.tearDown(self)

