# -*- coding: utf-8 -*-

import unittest

from HTMLTestRunner import HTMLTestRunner
from roomis.testcase.test_managespace import Testmanagespace
from roomis.testcase.test_spacebooking import Testspacebooking

if __name__ == '__main__':
    suite = unittest.TestSuite()

    testspacebookings = [Testspacebooking("test_1createbooking"), Testspacebooking("test_2canclebooking")]
    testmanagespaces = [Testmanagespace("test_createspace"), Testmanagespace("test_deletespace")]
    suite.addTests(testspacebookings)
    suite.addTests(testmanagespaces)
    with open('HTMLReport.html', 'wb') as tf:
        runner = HTMLTestRunner(stream=tf,
                                title='Roomis Test Report',
                                description='Roomis Test Report generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)

